logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:8889/ejercicioEvaludacion?useSSL=false&&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
